#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 16, local_size_y = 16) in;

layout(push_constant) uniform sim_buffer_params {
    uint pixelWidth;
    uint pixelHeight;
    uint columnStride;
    uint totalPixels;
};

layout (binding=0) buffer readonly sim_buffers {
    float velocity_x[];
    float velocity_y[];
    float pressure[];
    int fluidmask[];
};
layout (binding=1,rgba32f) uniform writeonly image2D resultImage;

void main() {
    // TODO
    vec4 value = vec4(0, 1, 5, 1);
    imageStore(resultImage, ivec2(gl_GlobalInvocationID.xy), value);
}
